/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ValidateEmailRouteImport } from './routes/validate-email'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as BriefsIndexRouteImport } from './routes/briefs/index'
import { Route as BriefsIdRouteImport } from './routes/briefs/$id'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram.webhook'
import { Route as ApiBriefsAudioFileIdRouteImport } from './routes/api/briefs.audio.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateEmailRoute = ValidateEmailRouteImport.update({
  id: '/validate-email',
  path: '/validate-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BriefsIndexRoute = BriefsIndexRouteImport.update({
  id: '/briefs/',
  path: '/briefs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsIdRoute = BriefsIdRouteImport.update({
  id: '/briefs/$id',
  path: '/briefs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefsAudioFileIdRoute = ApiBriefsAudioFileIdRouteImport.update({
  id: '/api/briefs/audio/$fileId',
  path: '/api/briefs/audio/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRoute
  '/validate-email': typeof ValidateEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/briefs/': typeof BriefsIndexRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/briefs/audio/$fileId': typeof ApiBriefsAudioFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRoute
  '/validate-email': typeof ValidateEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/admin': typeof AdminIndexRoute
  '/briefs': typeof BriefsIndexRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/briefs/audio/$fileId': typeof ApiBriefsAudioFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRoute
  '/validate-email': typeof ValidateEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/briefs/$id': typeof BriefsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/briefs/': typeof BriefsIndexRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/briefs/audio/$fileId': typeof ApiBriefsAudioFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/home'
    | '/how-it-works'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/topics'
    | '/validate-email'
    | '/admin/categories'
    | '/briefs/$id'
    | '/admin/'
    | '/briefs/'
    | '/api/telegram/webhook'
    | '/api/briefs/audio/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/home'
    | '/how-it-works'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/topics'
    | '/validate-email'
    | '/admin/categories'
    | '/briefs/$id'
    | '/admin'
    | '/briefs'
    | '/api/telegram/webhook'
    | '/api/briefs/audio/$fileId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/home'
    | '/how-it-works'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/topics'
    | '/validate-email'
    | '/admin/categories'
    | '/briefs/$id'
    | '/admin/'
    | '/briefs/'
    | '/api/telegram/webhook'
    | '/api/briefs/audio/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopicsRoute: typeof TopicsRoute
  ValidateEmailRoute: typeof ValidateEmailRoute
  BriefsIdRoute: typeof BriefsIdRoute
  BriefsIndexRoute: typeof BriefsIndexRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiBriefsAudioFileIdRoute: typeof ApiBriefsAudioFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate-email': {
      id: '/validate-email'
      path: '/validate-email'
      fullPath: '/validate-email'
      preLoaderRoute: typeof ValidateEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/briefs/': {
      id: '/briefs/'
      path: '/briefs'
      fullPath: '/briefs/'
      preLoaderRoute: typeof BriefsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs/$id': {
      id: '/briefs/$id'
      path: '/briefs/$id'
      fullPath: '/briefs/$id'
      preLoaderRoute: typeof BriefsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/briefs/audio/$fileId': {
      id: '/api/briefs/audio/$fileId'
      path: '/api/briefs/audio/$fileId'
      fullPath: '/api/briefs/audio/$fileId'
      preLoaderRoute: typeof ApiBriefsAudioFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopicsRoute: TopicsRoute,
  ValidateEmailRoute: ValidateEmailRoute,
  BriefsIdRoute: BriefsIdRoute,
  BriefsIndexRoute: BriefsIndexRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiBriefsAudioFileIdRoute: ApiBriefsAudioFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
