export const API_ERROR = {
	AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
	AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
	AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
	AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
	AUTH_INVALID_SESSION: "AUTH_INVALID_SESSION",
	AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
	AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
} as const;
