export const DOMAIN_ERROR_CODE = {
	CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
	SUBSCRIPTION_CATEGORY_DISABLED: "SUBSCRIPTION_CATEGORY_DISABLED",
	SUBSCRIPTION_CATEGORY_NOT_FOUND: "SUBSCRIPTION_CATEGORY_NOT_FOUND",
} as const;
