/** Codes for InternalError — bugs and invariant violations, never surfaced as an HTTP response. */
export const INTERNAL_ERROR_CODE = {
	CATEGORY_JOB_CATEGORY_NOT_FOUND: "CATEGORY_JOB_CATEGORY_NOT_FOUND",
	CATEGORY_JOB_MISSING_SUMMARY: "CATEGORY_JOB_MISSING_SUMMARY",
	CATEGORY_JOB_STATE_CONFLICT: "CATEGORY_JOB_STATE_CONFLICT",
	CATEGORY_JOB_UNKNOWN_STATE: "CATEGORY_JOB_UNKNOWN_STATE",
	CONNECTOR_FETCH_ERROR: "CONNECTOR_FETCH_ERROR",
	CONNECTOR_PARSE_ERROR: "CONNECTOR_PARSE_ERROR",
	CONNECTOR_TIMEOUT: "CONNECTOR_TIMEOUT",
	FILE_DOWNLOAD_FAILED: "FILE_DOWNLOAD_FAILED",
	FILE_NOT_FOUND: "FILE_NOT_FOUND",
	FILE_TOO_LARGE: "FILE_TOO_LARGE",
	FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
	NO_ARTICLES_SELECTED: "NO_ARTICLES_SELECTED",
	NO_CONNECTOR: "NO_CONNECTOR",
	TTS_INPUT_TOO_LONG: "TTS_INPUT_TOO_LONG",
	TTS_NO_AUDIO: "TTS_NO_AUDIO",
} as const;
