import { CONNECTOR_KIND } from "./connectors.constant.js";

/**
 * The media the RSS connector is known to ingest. It is not a hard whitelist —
 * any RSS feed works — but it is the list the seed installs and the one the
 * connector's network smoke test runs against, so the two never drift.
 */
export const SEED_PROVIDERS = [
	{
		name: "France Info",
		slug: "france-info",
		url: "https://www.franceinfo.fr/titres.rss",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "France 24",
		slug: "france-24",
		url: "https://www.france24.com/fr/france/rss",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Huffpost",
		slug: "huffpost",
		url: "https://www.huffingtonpost.fr/rss/all_full.xml",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "RFI",
		slug: "rfi",
		url: "https://www.rfi.fr/fr/france/rss",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "20 Minutes",
		slug: "20-minutes",
		url: "https://www.20minutes.fr/feeds/rss-une.xml",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Public Sénat",
		slug: "public-senat",
		url: "https://www.publicsenat.fr/feed",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Radio-Canada Info",
		slug: "radio-canada",
		url: "https://ici.radio-canada.ca/rss/4159",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "RTBF Info",
		slug: "rtbf",
		url: "https://rss.rtbf.be/article/rss/highlight_rtbf_info.xml",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Global Voices FR",
		slug: "global-voices-fr",
		url: "https://fr.globalvoices.org/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Frandroid",
		slug: "frandroid",
		url: "https://www.frandroid.com/feed",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Slate",
		slug: "slate",
		url: "https://slate.com/feeds/news-and-politics.rss",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Futura",
		slug: "futura",
		url: "https://www.futura-sciences.com/rss/actualites.xml",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "The Conversation FR",
		slug: "the-conversation-fr",
		url: "https://theconversation.com/fr/articles.atom",
		kind: CONNECTOR_KIND.ATOM,
	},
	{
		name: "Africanews FR",
		slug: "africanews-fr",
		url: "https://fr.africanews.com/feed/rss?themes=news",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Africanews EN",
		slug: "africanews-en",
		url: "https://www.africanews.com/feed/rss?themes=news",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "AllAfrica FR",
		slug: "allafrica-fr",
		url: "https://fr.allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "AllAfrica EN",
		slug: "allafrica-en",
		url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Algérie360",
		slug: "algerie-360",
		url: "https://www.algerie360.com/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Aujourd'hui le Maroc",
		slug: "aujourdhui-le-maroc",
		url: "https://aujourdhui.ma/feed",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Atlasinfo",
		slug: "atlasinfo",
		url: "https://atlasinfo.fr/feed",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "EUobserver",
		slug: "euobserver",
		url: "https://euobserver.com/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "European Interest",
		slug: "european-interest",
		url: "https://www.europeaninterest.eu/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Euronews Europe FR",
		slug: "euronews-europe-fr",
		url: "https://fr.euronews.com/rss?level=vertical&name=my-europe",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Euronews Europe EN",
		slug: "euronews-europe-en",
		url: "https://www.euronews.com/rss?level=vertical&name=my-europe",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Le Grand Continent",
		slug: "le-grand-continent",
		url: "https://legrandcontinent.eu/fr/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Brussels Signal",
		slug: "brussels-signal",
		url: "https://brusselssignal.eu/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Social Europe",
		slug: "social-europe",
		url: "https://www.socialeurope.eu/feed",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "TechCrunch",
		slug: "techcrunch",
		url: "https://techcrunch.com/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Tom's Hardware",
		slug: "toms-hardware",
		url: "https://www.tomshardware.com/feeds.xml",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "BleepingComputer",
		slug: "bleepingcomputer",
		url: "https://www.bleepingcomputer.com/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "SecurityWeek",
		slug: "securityweek",
		url: "https://www.securityweek.com/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Phoronix",
		slug: "phoronix",
		url: "https://www.phoronix.com/rss.php",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "IEEE Spectrum",
		slug: "ieee-spectrum",
		url: "https://spectrum.ieee.org/feeds/feed.rss",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Google Research",
		slug: "google-research",
		url: "https://research.google/blog/rss/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Hugging Face Blog",
		slug: "hugging-face-blog",
		url: "https://huggingface.co/blog/feed.xml",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Simon Willison's Weblog",
		slug: "simon-willison",
		url: "https://simonwillison.net/atom/entries/",
		kind: CONNECTOR_KIND.ATOM,
	},
	{
		name: "Basket USA",
		slug: "basket-usa",
		url: "https://www.basketusa.com/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "ClutchPoints NBA",
		slug: "clutchpoints-nba",
		url: "https://clutchpoints.com/nba/feed",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "But! Football Club",
		slug: "but-football-club",
		url: "https://www.butfootballclub.fr/feed/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "football.london",
		slug: "football-london",
		url: "https://www.football.london/all-about/premier-league/?service=rss",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "TuttoMercatoWeb",
		slug: "tuttomercatoweb",
		url: "https://www.tuttomercatoweb.com/rss/",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Sportschau Bundesliga",
		slug: "sportschau-bundesliga",
		url: "https://www.sportschau.de/fussball/bundesliga/index~rss2.xml",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Marca",
		slug: "marca",
		url: "https://www.marca.com/rss/portada.xml",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Sportschau",
		slug: "sportschau",
		url: "https://www.sportschau.de/index~rss2.xml",
		kind: CONNECTOR_KIND.RSS,
	},
	{
		name: "Sport.fr",
		slug: "sport-fr",
		url: "https://www.sport.fr/feed",
		kind: CONNECTOR_KIND.RSS,
	},
] as const;
